### ISSUE TITLE
hasPermission() throws Exception

### ISSUE THREAD

**Issue by stoefln** [eliotstocker/Light-ControllerAPI#2]
I just integrated the light controller API into my service and as soon as I run it I am getting this stacktrace:

<pre>
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime: java.lang.RuntimeException: Unable to create service net.microtrash.wisperingtree.service.RecordService: java.lang.SecurityException: Permission Denial: reading tv.piratemedia.lightcontroler.api.APIProvider uri content://tv.piratemedia.lightcontroler.api/permission/net.microtrash.wisperingtree from pid=23481, uid=10308 requires tv.piratemedia.lightcontroler.api, or grantUriPermission()
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3110)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.access$1900(ActivityThread.java:172)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5832)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:  Caused by: java.lang.SecurityException: Permission Denial: reading tv.piratemedia.lightcontroler.api.APIProvider uri content://tv.piratemedia.lightcontroler.api/permission/net.microtrash.wisperingtree from pid=23481, uid=10308 requires tv.piratemedia.lightcontroler.api, or grantUriPermission()
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1540)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.content.ContentResolver.query(ContentResolver.java:484)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.content.ContentResolver.query(ContentResolver.java:428)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at tv.piratemedia.lightcontroler.api.LightControllerAPI.hasPermission(LightControllerAPI.java:168)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at net.microtrash.wisperingtree.service.RecordService.onCreate(RecordService.java:87)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3100)
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.access$1900(ActivityThread.java:172) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5832) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
11-21 00:06:10.918 23481-23481/net.microtrash.wisperingtree E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
</pre>

The code is running in a service:

<pre>
public class RecordService extends Service {
 @Override
    public void onCreate() {
        super.onCreate();

        try {
            mLightApi = new LightControllerAPI(this);

            if(mLightApi.hasPermission()) {
                LightZone[] zones = mLightApi.listZones();
                mLightZone = zones[zones.length - 1];
            } else {
                //app doesnt have permission, set event for if any permissions change on the api
                Toast.makeText(getBaseContext(), "App does not have permissions for light API!", Toast.LENGTH_LONG).show();
            }
        } catch(LightControllerException e) {
            if(e.getCode() == LightControllerException.TYPE_APPLICATION_MISSING) {
                //Light Controller application is not installed
                //open store to download Light Controller
                LightControllerAPI.getApplicationFromPlayStore(this);
            } else if(e.getCode() == LightControllerException.TYPE_APPLICATION_OLD) {
                //Light Controller application too old
                //open store to download Latest Light Controller
                LightControllerAPI.getApplicationFromPlayStore(this);
            }
        }

    }

 ...
</pre>

Can you help me?

**Comment by stoefln** [comment]
Just checked: It's also crashing when I run it inside a Fragment...

**Comment by eliotstocker** [comment]
Hi Stephan,

I will have a look at that later today and see if i can replicate the
issue, what Android Version are you running on? i suspect it could be to do
with the new Marshmallow Permissions model.

**Comment by stoefln** [comment]
No Marshmellow. Android 5.0

**Comment by stoefln** [comment]
I don't really see the purpose of this permission system. I found out that I can bypass your API by directly using the classes you are providing in your lightcontroller app. Thanks for those a lot BTW, its sooo handy!

**Comment by eliotstocker** [comment]
the permission system is to stop apps from randomly turning your lights on and off, do you mean the classing in the API or copying strait from light controller app?

**Comment by eliotstocker** [comment]
just had a check, and cant seem to replicate your issue, did you declare the lightcontroller permission in your manifest?

``` xml
<uses-permission android:name="tv.piratemedia.lightcontroler.api"/>
```

**Comment by stoefln** [comment]
yes, sure

**Comment by stoefln** [comment]
I meant copying straight from light controller app. I don't see what a permission system is good for if you can easily bypass it via UDPC. I see your point that it would be nice to have an option of preventing apps messing around with your lights though. But I don't see how your permission system would prevent them from doing so...

**Comment by eliotstocker** [comment]
closing this as i cant replicate the issue at all apart from one small issue on Marshmallow, i agree that other apps can implement light control directly, i just dont want apps using LightController without the users permission ideally the box would allow the user to set a password that would need to be sent with each UDP Package, but there is not much we can do about that right now.
